import jsPDF from "jspdf";
import logo from "../assets/logo.png";
const exportChatPDF = (messages) => {
  const doc = new jsPDF();
  // Logo
// ===== Header =====

// Total header width (logo + gap + text)
const headerWidth = 80;

// A4 width = 210
const startX = (210 - headerWidth) / 2;

// Logo
doc.addImage(
  logo,
  "PNG",
  startX,
  15,
  18,
  18
);

// Title
doc.setFont("helvetica", "bold");
doc.setFontSize(20);

doc.text(
  "Zentrix",
  startX + 22,   // <-- was around +25
  24             // <-- slightly higher
);

// Subtitle
doc.setFont("helvetica", "bold");   // jsPDF has normal/bold only
doc.setFontSize(10.5);

doc.text(
  "Intelligent AI Assistant",
  startX + 22,   // <-- same X as title
  30             // <-- closer to title
);
 
  doc.setDrawColor(0);
  doc.setLineWidth(0.3528);

doc.rect(
    10,
    10,
    190,
    277
);

  // Date
  doc.setFontSize(10);
  

doc.line(20, 42, 190, 42);
  let y = 55;

  messages.forEach((message) => {
    if (message.website) {
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);

  doc.text(`Website: ${message.website}`, 20, y);

  y += 8;

  doc.setTextColor(0, 0, 0);
}
    // Heading
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);

    const heading =
      message.role === "user" ? "USER" : "AI RESPONSE";

    if (message.role === "user") {
  doc.setTextColor(0, 102, 204); // Blue
} else {
  doc.setTextColor(0, 128, 0); // Green
}
const lines = doc.splitTextToSize(
  String(message.content),
  160
);

const boxHeight = lines.length * 7 + 10;

const pageHeight = 270;

if (y + boxHeight > pageHeight) {
  doc.addPage();

  // draw header...
  doc.setDrawColor(0);
doc.setLineWidth(0.3528);
doc.rect(10, 10, 190, 277);



doc.setFontSize(10);


doc.line(20, 95, 190, 95);

y = 110;

  y = 110;
}

// NOW draw heading
doc.text(heading, 20, y);

// Reset color
doc.setTextColor(0, 0, 0);

y += 8;

// Draw box
doc.setDrawColor(180,180,180);

doc.roundedRect(
  20,
  y,
  170,
  boxHeight,
  3,
  3
);

doc.text(
  lines,
  25,
  y + 7
);

y += boxHeight + 12;
    if (message.isImage) {
  try {
    doc.addImage(
      message.content,
      "PNG",
      25,
      y,
      80,
      80
    );

    y += 90;
  } catch (err) {
    doc.text("Generated Image", 25, y);
    y += 15;
  }

  return;
}

    

  


    
    
  });
  const totalPages = doc.getNumberOfPages();

for (let i = 1; i <= totalPages; i++) {
  doc.setPage(i);

  doc.setFontSize(9);

  doc.text(
    "Generated by Zentrix",
    105,
    285,
    { align: "center" }
  );

  doc.text(
    `Page ${i} of ${totalPages}`,
    180,
    285
  );
}

  doc.save("Zentrix-Chat.pdf");
};

export default exportChatPDF;